# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_logo_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='parent',
        ),
        migrations.AddField(
            model_name='nav',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Nav', verbose_name='关联一级菜单'),
        ),
    ]
