# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20190428_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='导航链接'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Nav', verbose_name='关联一级菜单'),
        ),
    ]
