# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20190428_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact1', models.ImageField(upload_to='static/common/contact', verbose_name='联系方式1地址')),
                ('contact1_info', models.CharField(blank=True, max_length=125, null=True, verbose_name='联系方式1 脚注')),
                ('contact2', models.ImageField(upload_to='static/common/contact', verbose_name='联系方式2地址')),
                ('contact2_info', models.CharField(blank=True, max_length=125, null=True, verbose_name='联系方式2 脚注')),
                ('jianjie', models.TextField(verbose_name='网站简介')),
                ('copyright', models.TextField(verbose_name='网站版权')),
                ('email_adress', models.CharField(max_length=128, verbose_name='联系邮箱')),
                ('record_number', models.CharField(max_length=46, verbose_name='备案号')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '页脚',
                'verbose_name_plural': '页脚',
            },
        ),
    ]
