# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='contact1',
            field=models.ImageField(blank=True, null=True, upload_to='static/common/contact', verbose_name='联系方式1地址'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='contact2',
            field=models.ImageField(blank=True, null=True, upload_to='static/common/contact', verbose_name='联系方式2地址'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright',
            field=models.TextField(blank=True, null=True, verbose_name='网站版权'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='email_adress',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='联系邮箱'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='jianjie',
            field=models.TextField(blank=True, null=True, verbose_name='网站简介'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='record_number',
            field=models.CharField(blank=True, max_length=46, null=True, verbose_name='备案号'),
        ),
    ]
