# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20190428_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('friends_name', models.CharField(max_length=48, verbose_name='友情链接名称')),
                ('friends_link', models.CharField(max_length=55, verbose_name='友情链接地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
    ]
